name: Run tests when pull request is created/modified

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install .
      - name: Run tests
        run: python easyPythonpi/test
